In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

Creating a dataset

In [2]:
from sklearn.datasets import make_classification

In [3]:
X,y = make_classification(n_samples=1000, n_features=10, n_classes=2,random_state=42)

In [4]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]], shape=(1000, 10))

In [5]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0    0.964799 -0.066449  0.986768 -0.358079  0.997266  1.181890 -1.615679   
1   -0.916511 -0.566395 -1.008614  0.831617 -1.176962  1.820544  1.752375   
2   -0.109484 -0.432774 -0.457649  0.793818 -0.268646 -1.836360  1.239086   
3    1.750412  2.023606  1.688159  0.006800 -1.607661  0.184741 -2.619427   
4   -0.224726 -0.711303 -0.220778  0.117124  1.536061  0.597538  0.348645   
..        ...       ...       ...       ...       ...       ...       ...   
995 -1.367638  1.462255 -1.154918 -0.290454 -0.413424  0.032396  1.545490   
996 -1.514876 -3.221016 -1.300744  0.395599 -0.527994  1.353069  1.777506   
997  1.674633  1.754933  1.586154  0.018402 -1.514470  0.321593 -2.417694   
998 -0.778609 -0.835689 -0.194842  1.097220  0.180071 -0.272933 -0.533188   
999  0.248454 -1.003439  0.360460 -0.331352  1.389764 -1.345210 -0.740875   

            7         8         9  
0   -1.210161 -0.628077  1.227274  
1   -0.984534  0.363896  0.209470  
2   -0.246383 -1.058145 -0.297376  
3   -0.357445 -1.473127 -0.190039  
4   -0.939156  0.175915  0.236224  
..        ...       ...       ...  
995  1.428760  1.687092  1.072542  
996 -1.680870  1.798510  0.034272  
997  0.692723 -1.503850  0.225264  
998 -0.497354  2.472138  0.867187  
999  0.773240  0.185734  1.416412  

[1000 rows x 10 columns]

In [6]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [7]:
pd.DataFrame(y)

0
0    0
1    1
2    1
3    0
4    1
..  ..
995  1
996  1
997  0
998  0
999  0

[1000 rows x 1 columns]

Train test split

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [10]:
pd.DataFrame(X_train)

0         1         2         3         4         5         6  \
0    0.044467  0.913772 -0.149724 -1.545730 -1.092164  0.834751  0.521719   
1    0.417228 -0.745942  0.603095 -0.661541 -1.239562 -1.502871 -1.237353   
2    0.838689  0.860183  0.663881  0.810260 -0.458877 -1.017585 -0.812271   
3   -1.199700  0.193449 -1.019683  1.309865  0.023081  0.624904  1.375817   
4    0.740765 -0.320668  0.620582  1.795211  0.534506  0.887655 -0.821929   
..        ...       ...       ...       ...       ...       ...       ...   
695  0.582967 -0.925425  0.422577  0.255384 -1.013896  0.085687 -0.445852   
696 -0.538786  1.534482 -0.635001  1.122374  1.096547 -2.191254  1.158654   
697  0.040915  0.427963 -0.002353  1.723075 -0.160560 -0.555286  0.066475   
698  0.339379 -0.640154  0.252540  1.483744 -1.085748  0.029796 -0.279510   
699  1.848152 -0.313058  1.780696 -0.000709  1.484116  0.355613 -2.760416   

            7         8         9  
0    0.574071 -0.666738  1.589839  
1   -0.614539  0.304630  0.753419  
2    0.725081 -1.179530 -1.155452  
3   -0.184551  1.458419 -0.074345  
4    0.497743 -0.930020  0.230071  
..        ...       ...       ...  
695 -0.408101 -0.946922 -0.895346  
696  0.543391  0.076465 -0.459765  
697 -1.922772 -0.171048  1.639257  
698 -1.399228 -0.529912 -0.734811  
699  0.604515 -1.561028 -1.250408  

[700 rows x 10 columns]

In [11]:
pd.DataFrame(X_test)

0         1         2         3         4         5         6  \
0    0.740306  0.425490  0.603912  1.197247  1.159074 -0.336255 -0.771684   
1   -1.495778  0.381353 -1.276334  1.365526  1.388665  0.142378  1.730630   
2   -0.144079 -0.009289  0.023662  0.306981 -0.175378  0.491506 -0.281049   
3   -0.287854  0.627606 -0.443368 -0.279507  1.320414 -0.874436  0.936993   
4   -0.209246 -0.177596  0.384766  0.655892  0.925975 -0.091076 -1.478354   
..        ...       ...       ...       ...       ...       ...       ...   
295 -0.138408  0.965327 -0.133261  0.704336  1.072930 -0.853399  0.206437   
296 -0.582599 -0.450994 -0.497786  0.293949  0.461272 -0.924357  0.676086   
297 -0.129320 -2.032354 -0.140782 -1.321556  0.432353 -0.717182  0.242577   
298  0.754375 -0.468496  0.145824 -0.758765 -1.911317  0.092979  0.647783   
299  0.773924 -2.488327  0.668371 -0.658248 -0.509807  0.034441 -0.919837   

            7         8         9  
0   -0.709441 -0.982650 -1.371674  
1    0.574042  1.802012 -0.630143  
2   -0.342879  0.652572  1.813408  
3   -0.183854 -0.299303 -0.158305  
4   -0.020099  2.092603  0.963907  
..        ...       ...       ...  
295 -0.417783  0.117216  1.852040  
296 -0.057964  0.699723 -0.772542  
297 -1.131067  0.056355  0.021093  
298 -0.653679 -2.535541  1.350852  
299 -0.982294 -0.906270  0.453509  

[300 rows x 10 columns]

In [12]:
pd.DataFrame(y_train)

0
0    0
1    0
2    1
3    1
4    0
..  ..
695  0
696  1
697  1
698  1
699  0

[700 rows x 1 columns]

In [13]:
pd.DataFrame(y_test)

0
0    0
1    1
2    1
3    1
4    0
..  ..
295  1
296  1
297  1
298  1
299  0

[300 rows x 1 columns]

Model Training

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logistic = LogisticRegression()

In [16]:
logistic.fit(X_train, y_train)

LogisticRegression()

Prediction

In [17]:
y_pred = logistic.predict(X_test)

In [18]:
pd.DataFrame(y_pred)

0
0    0
1    1
2    0
3    1
4    0
..  ..
295  1
296  1
297  1
298  1
299  0

[300 rows x 1 columns]

Checking the probability of prediction data with 2 output categories (not needed for this scenario though)

In [19]:
logistic.predict_proba(X_test)

array([[7.74477909e-01, 2.25522091e-01],
       [3.36684957e-02, 9.66331504e-01],
       [6.70682154e-01, 3.29317846e-01],
       [7.98668032e-02, 9.20133197e-01],
       [9.76616650e-01, 2.33833501e-02],
       [4.13572804e-02, 9.58642720e-01],
       [9.79028767e-01, 2.09712329e-02],
       [9.59367261e-01, 4.06327393e-02],
       [8.08520049e-01, 1.91479951e-01],
       [6.84954318e-01, 3.15045682e-01],
       [9.13669448e-01, 8.63305524e-02],
       [2.63597018e-01, 7.36402982e-01],
       [5.25844192e-01, 4.74155808e-01],
       [2.11912354e-01, 7.88087646e-01],
       [7.93592056e-01, 2.06407944e-01],
       [9.46621678e-01, 5.33783219e-02],
       [2.62957933e-02, 9.73704207e-01],
       [3.24212617e-01, 6.75787383e-01],
       [3.14803584e-01, 6.85196416e-01],
       [2.04956217e-01, 7.95043783e-01],
       [5.04587065e-01, 4.95412935e-01],
       [9.66703630e-01, 3.32963696e-02],
       [2.00514796e-01, 7.99485204e-01],
       [7.77891908e-01, 2.22108092e-01],
       [8.729863

In [20]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [21]:
score = accuracy_score(y_test,y_pred)
score

0.8466666666666667

Confusion Matrix

In [22]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[118,  17],
       [ 29, 136]])

Precision and Recall values using classification report

In [23]:
classification_rep = classification_report(y_test, y_pred)
print(classification_rep)

              precision    recall  f1-score   support

           0       0.80      0.87      0.84       135
           1       0.89      0.82      0.86       165

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300



### Hyperparameter tuning and cross validation

In [24]:
model =  LogisticRegression()

In [25]:
penalty = ['l1', 'l2', 'elasticnet']

In [26]:
c_values = [100, 10, 1.0, 0.1, 0.01]

In [27]:
solver = ['lbfgs', 'liblinear', 'newton-cg', 'sag', 'saga']

In [28]:
params = dict(penalty=penalty, C=c_values, solver=solver)

In [29]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 1.0, 0.1, 0.01],
 'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag', 'saga']}

### Gridsearch CV for Hyperparameter tuning

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
from sklearn.model_selection import StratifiedKFold

In [32]:
cv= StratifiedKFold()

In [33]:
grid = GridSearchCV(estimator=model, param_grid=params, scoring='accuracy', cv=cv, n_jobs=-1)

In [34]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag',
                                    'saga']},
             scoring='accuracy')


In [35]:
grid.fit(X_train, y_train)

d:\Nivee\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
200 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg', 'sag',
                                    'saga']},
             scoring='accuracy')

In [36]:
grid.best_params_

{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}

In [37]:
grid.best_score_

np.float64(0.8785714285714287)

In [38]:
y_pred = grid.predict(X_test)

In [39]:
score = accuracy_score(y_test,y_pred)
score

0.8533333333333334

In [40]:
confusion_matrix(y_test, y_pred)

array([[124,  11],
       [ 33, 132]])

In [41]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



### Randomized Search CV

In [42]:
from sklearn.model_selection import RandomizedSearchCV

In [43]:
model = LogisticRegression()

In [44]:
randcv = RandomizedSearchCV(estimator=model, param_distributions=params, cv=5, scoring='accuracy')

In [45]:
randcv.fit(X_train, y_train)

d:\Nivee\myenv\Lib\site-packages\sklearn\model_selection\_validation.py:528: FitFailedWarning: 
25 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\model_selection\_validation.py", line 866, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1193, in fit
    solver = _check_solver(self.solver, self.penalty, s

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['lbfgs', 'liblinear',
                                                   'newton-cg', 'sag',
                                                   'saga']},
                   scoring='accuracy')

In [46]:
randcv.best_score_

np.float64(0.8785714285714287)

In [47]:
randcv.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}

In [48]:
y_pred = randcv.predict(X_test)

In [49]:
score = accuracy_score(y_test, y_pred)
score


0.8533333333333334

In [50]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.92      0.85       135
           1       0.92      0.80      0.86       165

    accuracy                           0.85       300
   macro avg       0.86      0.86      0.85       300
weighted avg       0.86      0.85      0.85       300



In [51]:
confusion_matrix(y_test, y_pred)

array([[124,  11],
       [ 33, 132]])

### Logistic Regression for Multiclass Classification 

In [52]:
X, y = make_classification(n_samples=1000, n_features=10,n_informative=3, n_classes=3, random_state=15)

In [53]:
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -1.286132 -0.648334  1.044115 -0.469715  0.789859 -0.083727 -1.647309   
1   -0.222224  2.083232  1.191114 -1.354527 -0.956992  1.696028 -1.070406   
2   -0.431963  0.375745 -1.370334  0.819214  0.345243  1.389447 -1.904130   
3   -0.912633  0.986988 -0.690042  2.014628 -0.442260  0.590347 -1.819353   
4   -0.367056  1.667892  0.879172  2.214276  1.846338 -0.894047  1.543838   
..        ...       ...       ...       ...       ...       ...       ...   
995 -2.496807  0.469077  0.095018 -0.216876  1.451541 -0.341269 -1.752938   
996  0.826337  0.510897 -0.389013  0.753788  0.282069  0.262201  0.159772   
997 -0.163846 -0.410725  0.739086 -0.102535  0.002940 -0.189182 -1.703856   
998  1.749691 -1.124168  0.199807 -0.841018  0.182736  1.827622 -0.047775   
999 -0.247556 -1.170594 -1.140586  0.444490 -0.125509 -0.635228  0.126535   

            7         8         9  
0   -1.316412  1.011910 -0.898063  
1    0.981403 -1.628798  1.377594  
2    1.292602  0.925545  0.232705  
3    1.560938  0.823755  0.517762  
4    0.931103 -1.015210  1.061845  
..        ...       ...       ...  
995 -2.607297 -0.219750 -0.622575  
996 -0.333163 -1.666029  0.538015  
997  0.558305  1.089718 -0.266273  
998  0.752557  0.322294 -0.173343  
999  0.206362  1.843518 -0.814831  

[1000 rows x 10 columns]

y has 0, 1 and 2 instead of 0 and 1 

In [54]:
pd.DataFrame(y)

0
0    2
1    0
2    0
3    0
4    1
..  ..
995  2
996  1
997  0
998  1
999  2

[1000 rows x 1 columns]

In [55]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [56]:
logistic_regression = LogisticRegression(multi_class='ovr')

In [57]:
logistic_regression.fit(X_train, y_train)

d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [58]:
y_pred = logistic_regression.predict(X_test)

In [59]:
y_pred

array([2, 1, 2, 1, 1, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 0, 0, 2, 2, 1,
       1, 1, 1, 0, 0, 0, 2, 1, 0, 2, 2, 1, 2, 0, 0, 2, 2, 1, 2, 2, 2, 1,
       2, 0, 1, 2, 0, 1, 0, 0, 0, 1, 1, 2, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       2, 1, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 1, 2,
       2, 1, 1, 2, 2, 0, 0, 0, 2, 2, 0, 1, 2, 1, 2, 1, 0, 2, 0, 2, 0, 1,
       2, 1, 2, 2, 1, 1, 1, 1, 2, 0, 2, 0, 1, 2, 0, 0, 2, 2, 2, 1, 2, 0,
       2, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1,
       2, 0, 2, 2, 2, 1, 0, 2, 0, 0, 2, 0, 2, 0, 0, 1, 2, 0, 1, 1, 1, 1,
       0, 2, 1, 0, 0, 1, 2, 2, 2, 2, 2, 0, 1, 1, 2, 2, 1, 2, 2, 2, 2, 1,
       0, 0, 1, 2, 2, 0, 0, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 2, 2, 1, 2, 1,
       0, 1, 0, 0, 1, 0, 2, 1, 0, 2, 2, 1, 1, 1, 2, 1, 1, 0, 1, 1, 0, 0,
       0, 0, 2, 0, 0, 2, 2, 2, 2, 0, 2, 0, 1, 2, 2, 2, 1, 0, 0, 1, 0, 2,
       1, 2, 0, 0, 0, 2, 2, 1, 2, 0, 1, 1, 0, 0, 0, 1, 0, 2, 2, 0, 2, 0,
       0, 0, 1, 1, 2, 0, 1, 2, 2, 0, 1, 2, 0, 2])

In [60]:
score = accuracy_score(y_test, y_pred)
score

0.79

In [61]:
confusion_matrix(y_test, y_pred)

array([[84, 10,  8],
       [ 3, 74, 25],
       [10,  7, 79]])

In [62]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.82      0.84       102
           1       0.81      0.73      0.77       102
           2       0.71      0.82      0.76        96

    accuracy                           0.79       300
   macro avg       0.79      0.79      0.79       300
weighted avg       0.80      0.79      0.79       300



### Logistic Regression for Imbalanced Dataset

In [63]:
from collections import Counter

In [64]:
from sklearn.datasets import make_classification

In [65]:
X, y = imbalanced_dataset = make_classification(n_samples=10000, n_features=2, n_clusters_per_class=1, n_redundant=0, weights=[0.99], random_state=10)

In [66]:
pd.DataFrame(X)

0         1
0     1.879910 -1.485035
1     0.377083 -2.238585
2     1.354312 -2.664638
3    -0.509843 -1.502950
4     0.863561 -1.906364
...        ...       ...
9995  1.066698 -0.548159
9996  1.058723 -0.933768
9997  0.995099 -0.541924
9998  1.758594 -1.549612
9999  0.797705 -1.994674

[10000 rows x 2 columns]

In [67]:
pd.DataFrame(y)

0
0     0
1     0
2     0
3     0
4     0
...  ..
9995  0
9996  0
9997  0
9998  0
9999  0

[10000 rows x 1 columns]

In [69]:
pd.DataFrame(y).value_counts()

0
0    9846
1     154
Name: count, dtype: int64

Train test split

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)


In [89]:
pd.DataFrame(y_train)

0
0     0
1     0
2     0
3     0
4     0
...  ..
7495  0
7496  0
7497  0
7498  0
7499  0

[7500 rows x 1 columns]

Hyperparameter Tuning

In [92]:
model = LogisticRegression()
penalty = ['l1', 'l2', 'elasticnet']
c_values = [100,10,0.1,1.0,0.01]
solver = ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga']
class_weight = [{0:a,1:b} for a in [1,10,50,100] for b in [1,10,50,100]]

In [93]:
class_weight

[{0: 1, 1: 1},
 {0: 1, 1: 10},
 {0: 1, 1: 50},
 {0: 1, 1: 100},
 {0: 10, 1: 1},
 {0: 10, 1: 10},
 {0: 10, 1: 50},
 {0: 10, 1: 100},
 {0: 50, 1: 1},
 {0: 50, 1: 10},
 {0: 50, 1: 50},
 {0: 50, 1: 100},
 {0: 100, 1: 1},
 {0: 100, 1: 10},
 {0: 100, 1: 50},
 {0: 100, 1: 100}]

In [94]:
params= dict(penalty=penalty, C=c_values, solver = solver, class_weight=class_weight)

In [95]:
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [100, 10, 0.1, 1.0, 0.01],
 'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'],
 'class_weight': [{0: 1, 1: 1},
  {0: 1, 1: 10},
  {0: 1, 1: 50},
  {0: 1, 1: 100},
  {0: 10, 1: 1},
  {0: 10, 1: 10},
  {0: 10, 1: 50},
  {0: 10, 1: 100},
  {0: 50, 1: 1},
  {0: 50, 1: 10},
  {0: 50, 1: 50},
  {0: 50, 1: 100},
  {0: 100, 1: 1},
  {0: 100, 1: 10},
  {0: 100, 1: 50},
  {0: 100, 1: 100}]}

In [96]:
grid = GridSearchCV(estimator=model, param_grid=params,scoring='accuracy', cv=cv)

In [99]:
grid.fit(X_train, y_train)

d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
d:\Nivee\myenv\Lib\site-packages\sklearn\linear_model\_sag.py:348: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warning

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(),
             param_grid={'C': [100, 10, 0.1, 1.0, 0.01],
                         'class_weight': [{0: 1, 1: 1}, {0: 1, 1: 10},
                                          {0: 1, 1: 50}, {0: 1, 1: 100},
                                          {0: 10, 1: 1}, {0: 10, 1: 10},
                                          {0: 10, 1: 50}, {0: 10, 1: 100},
                                          {0: 50, 1: 1}, {0: 50, 1: 10},
                                          {0: 50, 1: 50}, {0: 50, 1: 100},
                                          {0: 100, 1: 1}, {0: 100, 1: 10},
                                          {0: 100, 1: 50}, {0: 100, 1: 100}],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [100]:
grid.best_params_

{'C': 0.01,
 'class_weight': {0: 10, 1: 50},
 'penalty': 'l2',
 'solver': 'newton-cg'}

In [102]:
y_pred = grid.predict(X_test)

In [103]:
score = accuracy_score(y_test, y_pred)
print(score)
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

0.992
[[2468    2]
 [  18   12]]
              precision    recall  f1-score   support

           0       0.99      1.00      1.00      2470
           1       0.86      0.40      0.55        30

    accuracy                           0.99      2500
   macro avg       0.92      0.70      0.77      2500
weighted avg       0.99      0.99      0.99      2500



### ROC, AUC Curve (Threshold from 0.5 to other values)

In [ ]:
from sklearn.metrics import roc_curve, roc_auc_score


Generate 2 class dataset

In [107]:
X, y = make_classification(n_samples=1000, n_classes=2, random_state=1)

In [109]:
pd.DataFrame(y)

0
0    0
1    0
2    0
3    1
4    1
..  ..
995  1
996  0
997  1
998  1
999  0

[1000 rows x 1 columns]

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [112]:
pd.DataFrame(X_train)


0         1         2         3         4         5         6   \
0   -0.695554  0.614836  1.274758 -0.532406 -0.356561 -0.489235 -0.707218   
1    1.392883  0.075783 -0.378196 -1.658306 -0.293047 -0.068694 -2.172819   
2   -0.883024 -0.071713 -1.217081  0.574860 -1.199921 -1.111537  2.012857   
3   -0.240198  0.182073  0.310628  1.116091 -0.839369  1.762061 -0.163572   
4   -0.704313  0.093413  0.207295 -0.755992 -0.216813 -0.689219  0.445453   
..        ...       ...       ...       ...       ...       ...       ...   
745  0.395540  1.072972 -0.895882  1.739335 -0.612385  2.271310 -0.879935   
746 -1.251367 -1.027498 -0.478317  1.759403  1.378909  0.481494 -1.141341   
747  0.638099  0.623352  1.571161  0.341676 -1.271217  0.961930  0.279319   
748  1.169935 -1.609238 -0.930907 -1.757141  2.005300 -0.265883  1.178246   
749 -0.120699 -0.187696 -0.360571  0.739010  1.298023  0.932812  1.035768   

           7         8         9         10        11        12        13  \
0    1.110338 -0.003193 -1.330769  0.680508  0.854051 -1.473821 -1.471787   
1    0.795352  0.608325 -1.495019 -0.502025  0.744928 -0.610134 -0.488468   
2   -0.537908  0.445525 -1.027565  0.098533 -0.942571 -0.236009  0.783797   
3    0.294668  0.184577 -1.647663 -0.264364  1.745809  1.190380  0.257427   
4    0.471356  1.554829 -1.427323  0.177654 -0.876251 -1.775895  0.688391   
..        ...       ...       ...       ...       ...       ...       ...   
745 -0.051636 -0.109753  2.612907  0.322942  1.114772  2.716056  0.757800   
746  0.350121  0.475413  1.055492 -1.106000 -0.160217  0.900550 -0.605638   
747  0.367287  0.709420  0.498486 -0.953657  1.823909  1.160239  1.190285   
748  0.771315  0.217097  1.088889 -0.440581 -1.805383 -0.988658 -0.068421   
749 -0.421926  0.464270 -0.186080 -0.447256 -1.399627  0.831082 -0.276336   

           14        15        16        17        18        19  
0    0.367158 -1.358101  0.661556 -0.463184  2.445378  2.087214  
1   -1.038270 -0.637546 -1.715457 -1.330364  0.000803  1.143410  
2    0.605226 -0.751174 -1.525285  1.553357  1.153165 -0.092815  
3    0.271373  1.011337 -0.960501  0.476032  2.798819  0.916272  
4    0.347660 -0.638601  0.530070  0.157076  1.550482  1.066143  
..        ...       ...       ...       ...       ...       ...  
745 -0.049015  1.139579 -0.125787 -2.503811  1.338105 -1.838257  
746  0.962765  1.314743 -0.137757  0.897684 -0.069134  1.882874  
747 -0.353151 -1.057060  0.516842 -1.237400  2.896502  1.576916  
748 -0.912596  0.793833 -0.189343 -0.936556 -1.719884 -0.282823  
749  0.156181 -0.882016  1.322163 -0.242940 -1.501007  0.048745  

[750 rows x 20 columns]

In [113]:
pd.DataFrame(X_test)

0         1         2         3         4         5         6   \
0    0.331944  0.715367  1.324514  2.232038 -1.403135  1.063890 -0.148799   
1   -1.716008  0.071431 -0.225611  0.640793  1.497081  2.614008  0.388814   
2    0.261232  0.318616  0.444339 -0.184943 -0.265316  2.284830  1.367464   
3   -1.224033  1.991697  0.496865  1.691958  0.533306 -2.090451  0.423057   
4    1.406926  0.925779 -0.773255 -2.055402  1.569913  0.294119  0.241052   
..        ...       ...       ...       ...       ...       ...       ...   
245  1.272866  0.432564 -0.473145 -2.122486 -0.385953 -0.028240 -1.022741   
246 -0.895160  0.742342  0.529211  0.684536  0.472690  0.517272  0.165382   
247  1.528273 -2.467298  1.371324 -0.259394  0.237915 -0.529934 -1.851750   
248 -1.576782  0.405302  0.372912  2.112050 -0.624842  0.847417 -0.893118   
249  0.349130 -0.421527 -0.462762 -1.425676 -0.304237 -1.487786 -0.098292   

           7         8         9         10        11        12        13  \
0   -0.996426  0.010816  0.928495  0.920701  0.020065  3.289016 -1.584037   
1    0.746545 -1.132768 -1.591371  0.707294  0.007701 -1.081348  0.632308   
2   -0.674728  0.186350 -0.913816 -1.611229 -0.196164  0.050373  0.733650   
3    1.250891 -0.035138  0.387985  0.565697 -0.695670  0.842951 -0.527455   
4    0.627871  0.151166  1.280323  1.112255  0.035192 -1.113529 -1.150209   
..        ...       ...       ...       ...       ...       ...       ...   
245 -2.704221  0.924914  0.977632  0.449751 -0.167454 -1.351142 -1.618734   
246  0.026132 -1.131271  1.918620  1.244459  0.374576 -0.106209  0.604447   
247  1.240537  0.533795 -1.911544  0.038336  1.147566  1.369982 -0.096825   
248  0.309632 -0.660003 -0.505879 -2.148872 -0.088466  0.997629  0.330500   
249  1.322815  1.464925  0.339546 -1.529688  0.499258 -1.473264  0.381598   

           14        15        16        17        18        19  
0    0.044767 -1.650654  1.215780  0.277287 -0.511998  0.030002  
1    1.123176 -0.259195 -1.719392 -0.336061 -0.184083 -0.684141  
2   -0.180704 -0.823658  0.459589 -1.361913 -1.570737  2.324617  
3    0.938508 -0.207032 -1.280731  2.095090 -1.620799  1.222007  
4   -1.091043  1.262507 -0.599203  0.306839  0.416048  1.745560  
..        ...       ...       ...       ...       ...       ...  
245 -1.016326  0.074025 -0.885292  1.738106  1.907560  1.000074  
246  0.624864  1.072362  1.451335  0.320762  0.359017 -1.242301  
247 -0.965676 -2.232600 -0.219642 -0.785384 -0.435753 -1.136372  
248  1.201465  1.487305  0.910236  0.430973 -0.589812  0.443198  
249 -0.372579 -0.036244  1.340288  0.414212 -1.424054 -0.488879  

[250 rows x 20 columns]

In [114]:
pd.DataFrame(y_train)

0
0    0
1    0
2    0
3    0
4    0
..  ..
745  1
746  1
747  1
748  0
749  1

[750 rows x 1 columns]

In [115]:
pd.DataFrame(y_test)

0
0    1
1    0
2    0
3    1
4    0
..  ..
245  0
246  0
247  1
248  1
249  0

[250 rows x 1 columns]

Create a dummy model probability where all output is 0

In [118]:
dummy_model_prob = [0 for _ in range (len(y_test))]

In [120]:
pd.DataFrame(dummy_model_prob)

0
0    0
1    0
2    0
3    0
4    0
..  ..
245  0
246  0
247  0
248  0
249  0

[250 rows x 1 columns]

In [121]:
model = LogisticRegression()

In [122]:
model.fit(X_train, y_train)

LogisticRegression()

Prediction based on probability

In [123]:
model_probability = model.predict_proba(X_test)

In [126]:
pd.DataFrame(model_probability)

0         1
0    0.000959  0.999041
1    0.903113  0.096887
2    0.510628  0.489372
3    0.189953  0.810047
4    0.887573  0.112427
..        ...       ...
245  0.962743  0.037257
246  0.442068  0.557932
247  0.054615  0.945385
248  0.189323  0.810677
249  0.950721  0.049279

[250 rows x 2 columns]

Lets focus on 1 outcome

In [131]:
model_prob = model_probability[:, 1]
pd.DataFrame(model_prob)

0
0    0.999041
1    0.096887
2    0.489372
3    0.810047
4    0.112427
..        ...
245  0.037257
246  0.557932
247  0.945385
248  0.810677
249  0.049279

[250 rows x 1 columns]

Calculate the ROC AUC score

In [132]:
dummy_model_auc = roc_auc_score(y_test, dummy_model_prob)

In [134]:
dummy_model_auc

np.float64(0.5)

In [133]:
model_auc = roc_auc_score(y_test, model_prob)

In [135]:
model_auc

np.float64(0.9108885464817668)